### PR TITLE
Task estimation initial commit

### PR DESCRIPTION
**Pull request by tycyssg**
Here is my part on the task estimation topic. 
At least one of you has to verify this and then we can agree to merge it into the branch.

### CODE REVIEW

**Review by shanaia26 — APPROVED** [review]

**Review by aaronbermingham — COMMENTED** [review]
Content looks great! But I was thinking should we put each section in their own markdown file instead of in the readme one? What do you all think? @tycyssg @shanaia26 @AndrewQTUD

**Comment by tycyssg** [comment]
As far as I understand from what he said in class was this. Having the project plan in a different md file (this we did wrong at the start) and then merge into a single readme.md file all the content topics. It makes more sense to read everything from top to bottom than going to multiple files to read what we did but is up to you to decide how you want to do it.

**Comment by aaronbermingham** [comment]
Yeah that's grand. So we'll take out the project plan, put it in a separate file and keep the actual handbook content in the readme

**Review by aaronbermingham — APPROVED** [review]

**Review by AndrewQTUD — APPROVED** [review]

**Comment by aaronbermingham** [comment]
What's the process we want to follow for merging PRs, the person who created the PR does it or anyone in the group? And we want two approvals before merge, right?

**Comment by tycyssg** [comment]
It is up to us, to establish this rule. Usually, there are two options, either the person who creates the branch will do the merge or anyone else from the team. In the industry, the team lead will do the merging.

**Comment by aaronbermingham** [comment]
Ok cool, I'd go with the first option

**Pull request closed without merging**
